import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import {Header} from "@/app/components/header";
import {Footer} from "@/app/components/footer";
import Providers from "@/app/components/provider";

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" data-theme="fantasy">
        <head>
          <meta charSet="utf-8" />
          <title>Create Next App</title>
        </head>
      <body className={`${inter.className} justify-between flex flex-col min-h-screen calligraffitti`}>
        <Header />
            <Providers>{children}</Providers>
        <Footer />
      </body>
    </html>
  )
}
